# Paths
CLIPS_DIR = "../data/clips"
CVAT_DIR = "../data/CVAT_Style_labels"
OUTPUT_DIR = "D:/Repos/ms-aai-521-final-project/out"

# Data Split
TRAIN_PROPORTION = 0.6
VALIDATION_PROPORTION = 0.20
TEST_PROPORTION = 0.20

# Preprocessing
TARGET_FPS = 30
TARGET_RESOLUTION = (1280, 720)

# YOLO Training
YOLO_MODEL = 'yolo11m.pt'
TRAIN_EPOCHS = 100
TRAIN_BATCH_SIZE = 8
TRAIN_PATIENCE = 3
TRAIN_LEARNING_RATE = 0.00975
TRAIN_WEIGHT_DECAY = 0.00024
TRAIN_DROPOUT = 0.7


# Detection/Tracking
YOLO_BATCH_SIZE = 8
CONFIDENCE_THRESHOLD = 0.5
IOU = 0.67
TRACK_BUFFER = 46
MATCH_THRESHOLD = 0.62
TRACK_LOW_THRESHOLD = 0.46
TRACK_HIGH_THRESHOLD = 0.87
NEW_TRACK_THRESHOLD = 0.21

# Model Evaluation
EVAL_BATCH_SIZE = 16

# Visualization
VIZ_BOX_THICKNESS = 2
VIZ_FONT_SCALE = 0.5
VIZ_DASH_LENGTH = 10
VIZ_FPS = 30
VIZ_CODEC = 'mp4v'

# Tuning
TUNING_TRIALS = 30
